[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "dspy_tests"
version = "0.1.0"
description = "Small API tests project"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.15"
requests = "*"
python-dotenv = "*"
scikit-learn = "*"
numpy = "*"
pydantic = "^2.12.5"
